### ISSUE TITLE
Getting unauthorized error

### ISSUE THREAD

**Issue by rizwanmindcrew12** [neto737/BitGoSDK-PHP#1]
Hello Neto737,

I am using this SDK for implementation of bitgo wallet. While I am running its function $bitgo->listWalletAddresses('xyz')

xyz = 'my API key'

giving me error 

Array ( [error] => unauthorized [name] => Unauthorized [requestId] => cja0w3yb55dvkj9rtcdx6nxck )

Can you please assist me on this. Why I am getting this error.

My skype name is rizwan.shaikh@mindcrewtech.com
 
Thanks.
Mo. Rizwan Shaikh

**Comment by neto737** [comment]
Hi,

The ‘xyz’ needs to be your primary address of wallet.

Like this:

$bitgo->listWalletAddresses(‘YOUR PRIMARY ADDRESS HERE’);

Your API key goes in class init, like:

$bitgo = new BitGoSDK(‘YOUR API KEY’);

In a few weeks I’ll release an update to this SDK.

**Comment by PranjalPathak** [comment]
Hello neto737,
As you said that I have to use this code 
"$bitgo->listWalletAddresses(‘YOUR PRIMARY ADDRESS HERE’);
Your API key goes in class init, like:
$bitgo = new BitGoSDK('YOUR API KEY’);"

But, I am using exactly the same code:
$bitgo->listWalletAddresses(‘2MwoyZkAj8NSvmBbb91WjUgJdwT1swyhB15’);  // my BTC wallet address 
$bitgo = new BitGoSDK('xpub661MyMwAqRbcEvNw4mfzmMSi1a9Vxmgnwhbzpv61xhAiib5uafREwuir1WmKmGSk548AuvjFszYfmXQ353hJmot93WaSukREvyecoQVXJ5q’); //my api public key


My test account credentials:
https://test.bitgo.com
email: pranjal.pathak@mindcrewtech.com
password: Mindcrewtech01@123

Please help me.

Thanks

**Comment by neto737** [comment]
If you are using testnet, you need to set true in init BitGoSDK, like this:

$bitgo = new BitGoSDK('YOUR API KEY', true);

Regards

**Comment by PranjalPathak** [comment]
I am using that variable
$sdk = new BitGoSDK('xpub661MyMwAqRbcEvNw4mfzmMSi1a9Vxmgnwhbzpv61xhAiib5uafREwuir1WmKmGSk548AuvjFszYfmXQ353hJmot93WaSukREvyecoQVXJ5q', true);
$createAddress = $sdk->listWallets(); //function to get wallet lists


But still getting error 
Array ( [error] => unauthorized [name] => Unauthorized [requestId] => cja12x1826oqnj3rt7f34isem )

**Comment by PranjalPathak** [comment]
I am also using the function "create address"
<?php
require_once 'classes/BitGoSDK.php';
$sdk = new BitGoSDK('xpub661MyMwAqRbcEvNw4mfzmMSi1a9Vxmgnwhbzpv61xhAiib5uafREwuir1WmKmGSk548AuvjFszYfmXQ353hJmot93WaSukREvyecoQVXJ5q', true);
$createAddress = $sdk->createAddress('2MwoyZkAj8NSvmBbb91WjUgJdwT1swyhB15',0);
print_r($createAddress);
?>

getting same error

**Comment by neto737** [comment]
I think your API key is from API v2, I'll update this class in a few days with new version of API.

**Comment by PranjalPathak** [comment]
Hi neto373,
Okay, got it. Now, can you please provide me v1 SDK so that I can integrate it with my project and can perform the functions.
Please help.

**Comment by PranjalPathak** [comment]
Please help me how can I use bitgo API with any version

**Comment by neto737** [comment]
Bro, you need to get a v1 API key, I don't know how you can get this. When I create a new API key BitGo give me an v1 API key.

**Comment by PranjalPathak** [comment]
1. Can you provide me the steps to integrate API that you are using? 

2. because whenever I create the account it gives me a pdf file of keycard and I am unable to find the issue now, each and every time it gives an unauthorized error.

3.  Please provide me the steps to get the key.

4. Also, can you please give me your skype id so that I can communicate to you because it 's urgent to integrate API for me as soon as possible and I am stuck.
[BitGo Keycard for My BitGo Wallet.pdf](https://github.com/neto737/BitGoSDK-PHP/files/1481206/BitGo.Keycard.for.My.BitGo.Wallet.pdf)


Thanks

**Comment by neto737** [comment]
1. Log in into your account.
1.1. Create a wallet (you can use an existing wallet if you want)
1.2. Go to "User Settings" and "Developer Options"
1.3. Click in "+ Add Access Token" and create a new Access Token
1.4. When you create your new access token you'll get your API key.

Following these steps you should get it.

Regards

**Comment by PranjalPathak** [comment]
Hello neto737,
Can you please give me the link to generate an API key from V1 (you are using). Because I am following the same steps you stated in above message but I think everytime i am generating the token and getting V2 token "v2x43f2be964c74f03cb680d31405af0df6897ca7ed76363ff93e76d892095da712". 

Please help.

**Comment by neto737** [comment]
This "v2" at the beginning of your token doesn't matter that you have a v2 token, just relax.

Here are the link that you are looking for: https://test.bitgo.com/settings#developerOptions

Regards

**Comment by neto737** [comment]
Hey, I'm working in a new version of BitGoSDK-PHP, I guess I'll release it in less than a month. Keep following this repository.

Kind regards

**Comment by iamazadk** [comment]
i am using your version 2 api. still getting the same problem
Array
(
    [error] => unauthorized
    [name] => Unauthorized
    [requestId] => cjgp8765y0pbbimrw8xym48le
)

can you tell me what i did wrong?

**Comment by neto737** [comment]
Can you provide more details?
A snippet of your code and what function you are using.

**Comment by iamazadk** [comment]
require 'vendor/autoload.php';

use neto737\BitGoSDK\BitGoSDK;
use neto737\BitGoSDK\Enum\CurrencyCode;

require_once 'BitGoSDK/BitGoSDK.php';
require_once 'BitGoSDK/Enum/CurrencyCode.php';

$token = 'mytokenFromTheDeveloperSection';

$coin = CurrencyCode::BITCOIN_TESTNET;

$bitgo = new BitGoSDK($token2, $coin, true);

$getWalletByAddress = $bitgo->getWalletByAddress('33d8y13MWVusgtN1BCEkwdbGAMFBbi7FoR');


//$listwallets = $bitgo->listWallets();

echo '<pre>';print_r($getWalletByAddress);exit;

used much of your functions. no luck

**Comment by neto737** [comment]
If you are using Composer use only:
```php
require 'vendor/autoload.php'
```

Instead of:

```php
require_once 'BitGoSDK/BitGoSDK.php';
require_once 'BitGoSDK/Enum/CurrencyCode.php';
```

By the way, your code seems you are using `$token2` that doesn't exists in your code snippet. I think your problem is just a use problem instead a library problem. If you want help in your code contact me at Telegram @neto737

Kind regards,
Neto

**Comment by iamazadk** [comment]
i just  misprint that $token2. its $token with me, problem is that your sdk is not working with testnet but working fine with bitcoin and litecoin etc.
what api we need to pass with bitcoin_testnet?

**Comment by neto737** [comment]
I’ve discovered your problem.

In getWalletByAddress you are using a mainnet address, but the SDK has setup to testnet, so you need to use a testnet address instead a mainnet address.

Kind regards
Neto

**Comment by iamazadk** [comment]
so where can i find the testnet addresses for bitcoin and litecoin, and testnet for api token also?

**Comment by neto737** [comment]
So, I think you are also using a mainnet API key. You can get the testnet API key and addresses at https://test.bitgo.com

Kind regards,
Neto

**Comment by iamazadk** [comment]
it works, i really appreciate your help.
i want to ask another question. is there any way to automatically create access token
and why we saving ip addresses?
ip changes automatically after few times

**Comment by neto737** [comment]
I think the best way to do this is using the BitGo Express.

Kind regards,
Neto
