### ISSUE TITLE
I am unable to implement php sdk in our system.

### ISSUE THREAD

**Issue by yogesh0296** [neto737/BitGoSDK-PHP#10]
Hey,
I am new in bitcoin integration. I want integrate your bitgo php sdk in our website built in codeigniter. But i am unable to setup your sdk in our system. Please guide me step by step that how to integrate this sdk.

Please tell me that what is "YOUR_WALLET_PASSPHRASE".

Thanks
Yogesh Goyal

**Comment by neto737** [comment]
Hi,

“YOUR_WALLET_PASSPHRASE” means your wallet password. The password you’ve
set when you was creating your wallet in your BitGo account.

**Comment by yogesh0296** [comment]
Thanks For your response.
When i hit this url http://localhost/bitgo-php/sendTransaction.php
it's show me NULL output on my screen.
Please tell me how to set up this sdk in our system.
Plz
Thanks

**Comment by yogesh0296** [comment]
can you give me your personal email. where i will send you all details and i can contact you as soon as possible.

**Comment by neto737** [comment]
neto737@live.com

**Comment by yogesh0296** [comment]
i want to integrate your php sdk in our system but i am stuck in setup so please tell me how to setup this sdk step by step. please help me.
Thank you
Yogesh Goyal
