### ISSUE TITLE
update getWalletAddresses()

### ISSUE THREAD

**Issue by AntonSY11** [neto737/BitGoSDK-PHP#11]
### BitGoSDK Version
"neto737/bitgosdk-php": "^2.1",
### Related Issues

Hello can you add search address by label. In bitgo documentation endpoint below has param `labelContains` which help us find address by label.  

`https://test.bitgo.com//api/v2/{coin}/wallet/{walletId}/addresses`

Thanks a lot)

**Comment by neto737** [comment]
Hi,

I've sent a new commit with this feature.
