### ISSUE TITLE
Error in BitGoExpress

### ISSUE THREAD

**Issue by andrestc18** [neto737/BitGoSDK-PHP#12]
I get a NULL response error with any function in BitGoExpress, both as a local server and in the cloud.
I leave the code used that is completely copied from the example.

$hostname = 'localhost';
$port = 3080;
$coin = CurrencyCode::BITCOIN_TESTNET;
$bitgoExpress = new BitGoExpress($hostname, $port, $coin);
$bitgoExpress->accessToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx';
$generateWallet = $bitgoExpress->generateWallet('LABEL', 'PASSPHRASE');
var_dump($generateWallet);

RESP: NULL

**Comment by neto737** [comment]
Hi,

Are you sure that your BitGoExpress node is running correctly?

**Comment by AntonSY11** [comment]
I have the same error, and my SDK is running correctly. I run SDK and made curl request `curl http://localhost:3080/api/v2/ping` and its work fine, also i made get request in postman and its works fine too. But when i tried to send the same request throught youre package, i got null. And doesnt matter which method i used
