### ISSUE TITLE
Bitgo Test Environment Send Transaction

### ISSUE THREAD

**Issue by AlagumeenaBogi** [neto737/BitGoSDK-PHP#13]
### BitGoSDK Version

version 2.1

### Related Issues

I want need to wallet passphrase value in send transaction??

### Other Notes

please share to me??
![wallet_bitgo](https://user-images.githubusercontent.com/29532413/67830989-c9767200-fb02-11e9-9e59-8be3ccf5ca30.png)

**Comment by neto737** [comment]
Yes, it's really needed as it is on BitGo API documentation: https://www.bitgo.com/api/v2/#operation/express.wallet.sendcoins

Your passphrase will be sent directly to BitGo servers, without any kind of intermediation in BitGoSDK-PHP code.
