### ISSUE TITLE
2.1.10 breaks createWalletAddress()

### ISSUE THREAD

**Issue by markgukov** [neto737/BitGoSDK-PHP#16]
### BitGoSDK Version

2.1.10

### Related Issues

https://github.com/neto737/BitGoSDK-PHP/commit/3002fbaca8c3191df351724d7210632141894903#diff-77d36084e24607dfce767db7e835c19fL231

`public function createWalletAddress(bool $allowMigrated = false, int $chain = 0, int $gasPrice = null, string $label = null)`

`public function createWalletAddress(int $chain = AddressType::P2SH_DEPOSIT, string $label = null, bool $lowPriority = false, int $gasPrice = null)`

Perhaps this warranted a major version increase instead?

**Comment by neto737** [comment]
Hi,

What exactly happened? This update is just to pair the options with the official BitGo documentation.

**Comment by markgukov** [comment]
Calling `$bitgo->createWalletAddress(false, 0, null, "Note here")` no longer works.

The label is now the third argument instead of the fourth, etc.

**Comment by neto737** [comment]
Replace `$bitgo->createWalletAddress(false, 0, null, "Note here");`

By `$bitgo->createWalletAddress(AddressType::P2SH_DEPOSIT, "Note here");`

You can also use `$bitgo->createWalletAddress(AddressType::BECH32_DEPOSIT, "Note here");` if you want to use Bech32 (native segwit) addresses.

**Comment by markgukov** [comment]
Yes, that's how it can be fixed. I'm just pointing out that it's going to break existing implementations.

**Comment by neto737** [comment]
You're completely right. I'll remove the version 2.1.10 and create a new one, the 2.2.0 (with these updates). What you think about it?

**Comment by markgukov** [comment]
That's definitely better. Thanks!
