### ISSUE TITLE
Bug found and fixed..

### ISSUE THREAD

**Issue by ProWagerSystems** [neto737/BitGoSDK-PHP#3]
In the getWalletAddress function you need to use execute('GET') as below, you didn't have the 'GET' and it was always returning null. Just FYI.

    public function getWalletAddress(string $wallet,$cointype,$id) {
        $this->url = $this->API_Endpoint . '/' . $cointype . '/wallet/' . $wallet . '/address/'.$id;
        $this->params = [
            'wallet' => $wallet
        ];
        return $this->execute('GET');
    }

**Comment by neto737** [comment]
Hi,

Thanks for this issue, it has been fixed in the new version.
I guess in less than a month I'll can release a new version.

**Comment by sevenbitsravina** [comment]
i am getting same issue please check this in sendtranscation
