### ISSUE TITLE
Send Transaction

### ISSUE THREAD

**Issue by prajit21** [neto737/BitGoSDK-PHP#5]
### BitGoSDK Version

Type here, e.g. 2.1

### Related Issues

Found anything that might be related to this? It might help us find the cause.

### Other Notes

Anything else?

**Comment by neto737** [comment]
Can you explain what happened?

**Comment by prajit21** [comment]
i have using BitGo Express with send transaction api in php.

**PHP Code..** 

$hostname = 'localhost';
$port = 3080;
$coin = 'tbtc';
$bitgoExpress = new BitGoExpress($hostname, $port, $coin);
$bitgoExpress->accessToken = 'my_access_token';
$bitgoExpress->walletId = 'my_wallle_id';

 $sendTransaction = $bitgoExpress->sendTransaction('address',1000000,'my_wallet_pass');

---------------------------------------

**Response**

{
  "error": "invalid numBlocks, expecting positive number greater than 1",
  "name": "Invalid",
  "requestId": "cjhvtg7v4154biwrxa6e3wc7w",
  "message": "invalid numBlocks, expecting positive number greater than 1"
}

**Comment by neto737** [comment]
Try it:

$sendTransaction = $bitgoExpress->sendTransaction('address',1000000,'my_wallet_pass', null, 1);

If it works, please close this issue. :)

**Comment by prajit21** [comment]
it's not working..
same error again.

**Comment by neto737** [comment]
Oh, my bad. Change the 1 for another number greater than 1, and try again, I guess it will work. You can check BitGo documentation to look what is happening. If you discover it please share here!

**Comment by prajit21** [comment]
i change 1  to 2 

**Response** 

{
  "error": "Please provide a non-negative integer value for minConfirms, got null",
  "name": "Invalid",
  "requestId": "cjhvv2ylc1kyrizrybh6k0eg9",
  "message": "Please provide a non-negative integer value for minConfirms, got null"
}

**Comment by neto737** [comment]
Do you have Telegram? Message me at: @neto737 and I’ll fix it with you. :)

**Comment by prajit21** [comment]
yes i have telegram please open link https://pastebin.com/4RWEDLAk

**Comment by prajit21** [comment]
i have send message to you let me know when you check

**Comment by neto737** [comment]
Issue solved, update released!
