### ISSUE TITLE
Cant figure out the api parameters

### ISSUE THREAD

**Issue by Cyberpwince** [neto737/BitGoSDK-PHP#8]
have used http://bitgo.com and port 3080 but its giving error

**Comment by neto737** [comment]
You cannot use http://bitgo.com as your BitGo Express node. You need to setup your own node to start using BitGo Express functions. You can find out the setup guide here: [BitGo Express](https://github.com/neto737/BitGoSDK-PHP/wiki/2.-BitGo-Express)

**Comment by Cyberpwince** [comment]
Alright can i get your contact where i can talk to you easily

**Comment by neto737** [comment]
Contact me directly via Telegram at @neto737

**Comment by Cyberpwince** [comment]
Done
