### ISSUE TITLE
Call to undefined method neto737\\BitGoSDK\\BitGoSDK

### ISSUE THREAD

**Issue by naruponk** [neto737/BitGoSDK-PHP#9]
PHP Fatal error:  Uncaught Error: Call to undefined method neto737\\BitGoSDK\\BitGoSDK::sendTransaction() in /var/www/html/test.php:7\nStack trace:\n#0 {main}\n  thrown in /var/www/html/test.php on line 7

PHP7.2 on CentosOS 7

composer already installed, please suggestion what I missed?

Thank you in advance

**Comment by neto737** [comment]
Please, show me your code.

**Comment by yogesh0296** [comment]
<?php

require 'vendor/autoload.php';

use neto737\BitGoSDK\BitGoSDK;
use neto737\BitGoSDK\BitGoExpress;
use neto737\BitGoSDK\Enum\CurrencyCode;

$hostname = 'localhost';
$port = 80;
$coin = CurrencyCode::BITCOIN_TESTNET;

$bitgo = new BitGoSDK('v2xe5221da7fb0a892b4e1c73799a955883f4a482fdb15e4a855861e13e2bbc6ba6', $coin, true);

/**
 * To send any transaction with BitGoExpress SDK you need to unlock your wallet
 * If you're not using testnet to send coins, you need to unlock your wallet with
 * your OTP password (2FA)
 */
$bitgo->unlockSession('0000000');

$bitgoExpress = new BitGoExpress($hostname, $port, $coin);
 print_r($bitgo); die;
$bitgoExpress->accessToken = 'v2xe5221da7fb0a892b4e1c73799a955883f4a482fdb15e4a855861e13e2bbc6ba6';
$bitgoExpress->walletId = '5d107c8eecbe279403900cbfbf8b9d54';


/**
 * Send the amount in satoshi
 */
$value_in_btc = 0.25;
$amount = BitGoSDK::toSatoshi($value_in_btc);

$sendTransaction = $bitgoExpress->sendTransaction('2NFfxvXpAWjKng7enFougtvtxxCJ2hQEMo4', $amount, 'here are my password');
var_dump($sendTransaction);

**Comment by lalit-mittal** [comment]
[neto737.zip](https://github.com/neto737/BitGoSDK-PHP/files/3342876/neto737.zip)
i am getting the same error.
please have a look at my code. i have wasted a lot of time but didn't get anything
thank you

**Comment by neto737** [comment]
> [neto737.zip](https://github.com/neto737/BitGoSDK-PHP/files/3342876/neto737.zip)
> i am getting the same error.
> please have a look at my code. i have wasted a lot of time but didn't get anything
> thank you

I need to know what is your real problem. You've sent just your files.

**Comment by shamuel22** [comment]
I have same error, I use your same example.

Fatal error: Uncaught Error: Class 'neto737\BitGoSDK\Enum\CurrencyCode' not found in

`require_once 'vendor/autoload.php';


use neto737\BitGoSDK\BitGoSDK;
use neto737\BitGoSDK\Enum\CurrencyCode;


$coin = CurrencyCode::BITCOIN_TESTNET;
$bitgo = new BitGoSDK('xxxxxxx', $coin, true);
$bitgo->walletId = 'xxxxxx';
$createAddress = $bitgo->createWalletAddress();
var_dump($createAddress);`

**Comment by neto737** [comment]
> [neto737.zip](https://github.com/neto737/BitGoSDK-PHP/files/3342876/neto737.zip)
> i am getting the same error.
> please have a look at my code. i have wasted a lot of time but didn't get anything
> thank you

You need to require my project in your composer, I've checked that in your vendor folder there isn't any neto737 folder with BitGoSDK-PHP files.

**Comment by neto737** [comment]
> I have same error, I use your same example.
> 
> Fatal error: Uncaught Error: Class 'neto737\BitGoSDK\Enum\CurrencyCode' not found in
> 
> `require_once 'vendor/autoload.php';
> 
> use neto737\BitGoSDK\BitGoSDK;
> use neto737\BitGoSDK\Enum\CurrencyCode;
> 
> $coin = CurrencyCode::BITCOIN_TESTNET;
> $bitgo = new BitGoSDK('xxxxxxx', $coin, true);
> $bitgo->walletId = 'xxxxxx';
> $createAddress = $bitgo->createWalletAddress();
> var_dump($createAddress);`

Hi,

Have you downloaded the code or used composer to install BitGoSDK files? You might haven't required the BitGoSDK files in your code, and it's causing the problem.

**Comment by shamuel22** [comment]
Solved! Now when I try to send a transaction, it returns a Null value

**Comment by neto737** [comment]
> Solved! Now when I try to send a transaction, it returns a Null value

You need to install the BitGo Express. You can find a step-by-step tutorial on our Wiki.

**Comment by ghost** [comment]
[bitgo_php.zip](https://github.com/neto737/BitGoSDK-PHP/files/3430684/bitgo_php.zip)

Fatal error: Uncaught Error: Class 'neto737\BitGoSDK\Enum\CurrencyCode' not found in

please have a look at my code. 
how can i solve this?
please help me.

**Comment by neto737** [comment]
> [bitgo_php.zip](https://github.com/neto737/BitGoSDK-PHP/files/3430684/bitgo_php.zip)
> 
> Fatal error: Uncaught Error: Class 'neto737\BitGoSDK\Enum\CurrencyCode' not found in
> 
> please have a look at my code.
> how can i solve this?
> please help me.

I can't help you if you don't give me a detailed information about your problem.
